version: '3.1'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URI: postgresql://pguser:pgpass@db:5432/pgdb
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_USER: pguser
      POSTGRES_DB: pgdb
    ports:
      - 5432:5432
